##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - autoconf
    - git
    - make
    - xz-utils

after_scripts:
  - make distcheck
