##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - autoconf
    - clang-tools
    - expect #required for unbuffer
    - git
    - make
    - xz-utils

build_scripts:
  - ./make-scanbuild
  - ./exit-warning
  - echo DISTRO_NAME ${DISTRO_NAME}
  - echo DISTRO_VERSION ${DISTRO_VERSION}
