##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  debian:
    # Useful URL: https://github.com/cafe-desktop/debian-packages
    - autoconf
    - git
    - make
    - xz-utils

build_scripts:
  - mkdir html-report
  - NOCONFIGURE=1 ./autogen.sh
  - ./configure
  - make
  - make check
  - make install

after_scripts:
  - make distcheck
